### ISSUE TITLE
Error when loading a notion page

### ISSUE THREAD

**Issue by MattiooFR** [ghosw/notion-inline-math-equations#1]
When I try to load a notion page with the plugin activated in Violentmonkey I receive this error

![image](https://user-images.githubusercontent.com/13595614/77654272-26226f80-6f71-11ea-98d8-9f82324cf63c.png)

**Comment by gh0stwin** [comment]
Hi @MattiooFR, if you use the updated code you should have no issues! Even though, if you run into more problems just let me know!  Thank you!

**Comment by MattiooFR** [comment]
It does work now, thank you @ghosw :)
